### ISSUE TITLE
0.8 startup crash

### ISSUE THREAD

**Issue by qriqii** [LixieWulf/Allure#60]
**OS:** Windows

**Build:** mindustry 139

---

**Issue:** startup crash with error "Runtime: Meshes can only be parsed as parts of planets."

**Method(s) To Reproduce:** it's a startup crash

**All Mods Used:** none except exotic

**Crash Logs:** Mindustry has crashed. How unfortunate.
Version: steam build 139
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8176mb
Cores: 12
Mods: exotic-mod:0.75 Incomplete Alpha

arc.util.ArcRuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Meshes can only be parsed as parts of planets.
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:208)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Meshes can only be parsed as parts of planets.
	at mindustry.mod.ContentParser$2.internalRead(ContentParser.java:342)
	at mindustry.mod.ContentParser$2.readValue(ContentParser.java:328)
	at arc.util.serialization.Json.readValue(Json.java:980)
	at arc.util.serialization.Json.readValue(Json.java:976)
	at mindustry.mod.ContentParser.lambda$new$11(ContentParser.java:593)
	at mindustry.type.Planet.load(Planet.java:294)
	at mindustry.mod.Mods.lambda$loadSync$11(Mods.java:343)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.mod.Mods.loadSync(Mods.java:340)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:357)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more
Caused by: java.lang.RuntimeException: Meshes can only be parsed as parts of planets.
	at mindustry.mod.ContentParser$1.lambda$new$19(ContentParser.java:223)
	at mindustry.mod.ContentParser$2.internalRead(ContentParser.java:340)
	... 19 more

---

**Place an X in this box to show you understand.**

- [x] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

**Comment by LixieWulf** [comment]
known issue, use latest BE of wait for build 140

**Comment by qriqii** [comment]
ok
